# Generated by Django 3.2.11 on 2022-05-31 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='nebulosite',
            fields=[
                ('nebulosite_id', models.AutoField(primary_key=True, serialize=False)),
                ('nebulosite', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='observation',
            fields=[
                ('observation_id', models.AutoField(primary_key=True, serialize=False)),
                ('id_ville', models.IntegerField()),
                ('nom', models.CharField(max_length=40)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('date', models.DateField()),
                ('ech', models.IntegerField()),
                ('t2m', models.FloatField()),
                ('hu2m', models.FloatField()),
                ('hu10m', models.FloatField()),
                ('hu1000hpa', models.FloatField()),
                ('hu925hpa', models.FloatField()),
                ('hu850hpa', models.FloatField()),
                ('hu700hpa', models.FloatField()),
                ('hu500hpa', models.FloatField()),
                ('hu300hpa', models.FloatField()),
                ('u10ff', models.FloatField()),
                ('u10dd', models.FloatField()),
                ('u10ddd', models.CharField(max_length=5)),
                ('u20ff', models.FloatField()),
                ('u20dd', models.FloatField()),
                ('u20ddd', models.CharField(max_length=5)),
                ('u50ff', models.FloatField()),
                ('u50dd', models.FloatField()),
                ('u50ddd', models.CharField(max_length=5)),
                ('u100ff', models.FloatField()),
                ('u100dd', models.FloatField()),
                ('u100ddd', models.CharField(max_length=5)),
                ('cape', models.FloatField()),
                ('psol', models.FloatField()),
                ('ch', models.FloatField()),
                ('cm', models.FloatField()),
                ('cl', models.FloatField()),
                ('rr', models.FloatField()),
                ('rr_gn', models.FloatField()),
                ('rr_cv', models.FloatField()),
                ('rr_sn', models.FloatField()),
                ('vcty', models.FloatField()),
                ('tn', models.FloatField()),
                ('tx', models.FloatField()),
                ('gtn', models.FloatField()),
                ('gtx', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='prevision',
            fields=[
                ('observation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.observation')),
                ('nebulosite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.nebulosite')),
            ],
        ),
        migrations.CreateModel(
            name='validation',
            fields=[
                ('prevision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.prevision')),
                ('nebulosite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.nebulosite')),
                ('valideur', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
