# Generated by Django 3.2.11 on 2022-06-02 18:11

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLmodels',
            fields=[
                ('MLmodel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('model_file', picklefield.fields.PickledObjectField(editable=False)),
                ('preprocesser_file', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
