# Generated by Django 3.2.11 on 2022-06-02 18:38

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_mlmodels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlmodels',
            old_name='preprocesser_file',
            new_name='metric',
        ),
        migrations.AddField(
            model_name='mlmodels',
            name='scaler_file',
            field=picklefield.fields.PickledObjectField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
