# Generated by Django 3.2.11 on 2022-06-06 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220606_0038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MLmodels',
        ),
    ]
